---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: "false"
    fluxcd.io/tag.grafana: semver:~6
spec:
  releaseName: prometheus-operator
  rollback:
    enable: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 8.9.2
  values:
    server:
      resources:
        requests:
          memory: 1500Mi
          cpu: 25m
        limits:
          memory: 2000Mi
    prometheusOperator:
      createCustomResource: true
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: rook-ceph-block
              resources:
                requests:
                  storage: 10Gi
        # tolerations:
        # - key: "arm"
        #   operator: "Exists"
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
    nodeExporter:
      serviceMonitor:
        relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
          - __meta_kubernetes_pod_node_name
          targetLabel: kubernetes_node
    kubelet:
      serviceMonitor:
        metricRelabelings:
        - action: replace
          sourceLabels:
          - node
          targetLabel: instance
    grafana:
      # image:
        # repository: grafana/grafana
        # tag: 6.5.2
      # tolerations:
      # - key: "arm"
      #   operator: "Exists"
      deploymentStrategy:
        type: Recreate
      podAnnotations:
        backup.velero.io/backup-volumes: storage
      persistence:
        enabled: true
        storageClassName: "rook-ceph-block"
        size: 10Gi
        accessModes:
        - ReadWriteOnce
      env:
        GF_EXPLORE_ENABLED: true
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
      plugins:
      - natel-discrete-panel
      - pr0ps-trackmap-panel
      - grafana-piechart-panel
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
          - name: 'teslamate'
            orgId: 1
            folder: Teslamate
            # folderUid: Nr4ofiDZk
            type: file
            disableDeletion: false
            editable: true
            # updateIntervalSeconds: -1
            allowUiUpdates: true
            options:
              path: /var/lib/grafana/dashboards/teslamate
      dashboards:
        default:
          nginx-dashboard:
            url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json
            datasource: Prometheus
          ceph-cluster:
            url: https://grafana.com/api/dashboards/2842/revisions/11/download
            datasource: Prometheus
          ceph-osd:
            url: https://grafana.com/api/dashboards/5336/revisions/3/download
            datasource: Prometheus
          ceph-pools:
            url: https://grafana.com/api/dashboards/5342/revisions/3/download
            datasource: Prometheus
          vernemq:
            url: https://raw.githubusercontent.com/vernemq/vernemq/master/metrics_scripts/grafana/VerneMQ%20Node%20Metrics.json
            datasource: Prometheus
          velero:
            url: https://grafana.com/api/dashboards/11055/revisions/2/download
            datasource: Prometheus
          flux:
            url: https://grafana.com/api/dashboards/10475/revisions/1/download
            datasource: Prometheus
          blocky:
            url: https://raw.githubusercontent.com/0xERR0R/blocky/master/docs/blocky-grafana.json
            datasource: Prometheus
          # cable-modem-stats:
          #   url: https://raw.githubusercontent.com/johnknapprs/k8s-gitops/master/monitoring/prometheus-operator/grafana-dashboards/cable_modem_stats.json
          #   datasource: influxdb
          # comcast-sucks:
          #   url: https://raw.githubusercontent.com/johnknapprs/k8s-gitops/master/monitoring/prometheus-operator/grafana-dashboards/comcast_sucks.json
          #   datasource: influxdb
          # home-assistant:
          #   url: https://raw.githubusercontent.com/johnknapprs/k8s-gitops/master/monitoring/prometheus-operator/grafana-dashboards/home_assistant.json
          #   datasource: influxdb
          # ups:
          #   url: https://raw.githubusercontent.com/johnknapprs/k8s-gitops/master/monitoring/prometheus-operator/grafana-dashboards/ups.json
          #   datasource: influxdb
          # netdata:
          #   url: https://raw.githubusercontent.com/johnknapprs/k8s-gitops/master/monitoring/prometheus-operator/grafana-dashboards/netdata.json
          #   datasource: Prometheus
        teslamate:
          charge-level:
            url: https://raw.githubusercontent.com/adriankumpf/teslamate/v1.17.1/grafana/dashboards/charge-level.json
            # datasource: TeslaMate
          charges:
            url: https://raw.githubusercontent.com/adriankumpf/teslamate/v1.17.1/grafana/dashboards/charges.json
            # datasource: TeslaMate
          charging-stats:
            url: https://raw.githubusercontent.com/adriankumpf/teslamate/v1.17.1/grafana/dashboards/charging-stats.json
            # datasource: TeslaMate
          drive-stats:
            url: https://raw.githubusercontent.com/adriankumpf/teslamate/v1.17.1/grafana/dashboards/drive-stats.json
            # datasource: TeslaMate
          drives:
            url: https://raw.githubusercontent.com/adriankumpf/teslamate/v1.17.1/grafana/dashboards/drives.json
            # datasource: TeslaMate
          efficiency:
            url: https://raw.githubusercontent.com/adriankumpf/teslamate/v1.17.1/grafana/dashboards/efficiency.json
            # datasource: TeslaMate
          locations:
            url: https://raw.githubusercontent.com/adriankumpf/teslamate/v1.17.1/grafana/dashboards/locations.json
            # datasource: TeslaMate
          mileage:
            url: https://raw.githubusercontent.com/adriankumpf/teslamate/v1.17.1/grafana/dashboards/mileage.json
            # datasource: TeslaMate
          overview:
            url: https://raw.githubusercontent.com/adriankumpf/teslamate/v1.17.1/grafana/dashboards/overview.json
            # datasource: TeslaMate
          projected-range:
            url: https://raw.githubusercontent.com/adriankumpf/teslamate/v1.17.1/grafana/dashboards/projected-range.json
            # datasource: TeslaMate
          states:
            url: https://raw.githubusercontent.com/adriankumpf/teslamate/v1.17.1/grafana/dashboards/states.json
            # datasource: TeslaMate
          trip:
            url: https://raw.githubusercontent.com/adriankumpf/teslamate/v1.17.1/grafana/dashboards/trip.json
            # datasource: TeslaMate
          updates:
            url: https://raw.githubusercontent.com/adriankumpf/teslamate/v1.17.1/grafana/dashboards/updates.json
            # datasource: TeslaMate
          vampire-drain:
            url: https://raw.githubusercontent.com/adriankumpf/teslamate/v1.17.1/grafana/dashboards/vampire-drain.json
            # datasource: TeslaMate
          visited:
            url: https://raw.githubusercontent.com/adriankumpf/teslamate/v1.17.1/grafana/dashboards/visited.json
            # datasource: TeslaMate
          charge-details:
            url: https://raw.githubusercontent.com/adriankumpf/teslamate/v1.17.1/grafana/dashboards/internal/charge-details.json
          drive-details:
            url: https://raw.githubusercontent.com/adriankumpf/teslamate/v1.17.1/grafana/dashboards/internal/drive-details.json
      additionalDataSources:
      - name: loki
        type: loki
        access: proxy
        url: http://loki.logs.svc.cluster.local:3100
      - name: influxdb
        type: influxdb
        access: proxy
        url: http://influxdb:8086
        database: telegraf
      - name: cable_modem_stats
        type: influxdb
        access: proxy
        url: http://influxdb:8086
        database: cable_modem_stats
      - name: comcast
        type: influxdb
        access: proxy
        url: http://influxdb:8086
        database: comcast
      - name: home_assistant
        type: influxdb
        access: proxy
        url: http://influxdb:8086
        database: home_assistant
      - name: speedtests
        type: influxdb
        access: proxy
        url: http://influxdb:8086
        database: speedtests
      - name: uptimerobot
        type: influxdb
        access: proxy
        url: http://influxdb:8086
        database: uptimerobot
      grafana.ini:
        paths:
          data: /var/lib/grafana/data
          logs: /var/log/grafana
          plugins: /var/lib/grafana/plugins
          provisioning: /etc/grafana/provisioning
        analytics:
          check_for_updates: true
        log:
          mode: console
        grafana_net:
          url: https://grafana.net
    kubeEtcd:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    prometheus-node-exporter:
      tolerations:
      - key: "arm"
        operator: "Exists"
      - key: "armhf"
        operator: "Exists"
    prometheus:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
      prometheusSpec:
#        image:
#          repository: quay.io/prometheus/prometheus
#          tag: v2.9.1
        ruleSelector: {}
        ruleNamespaceSelector: {}
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelector: {}
        podMonitorNamespaceSelector: {}
        podMonitorSelectorNilUsesHelmValues: false
        retention: 30d
        enableAdminAPI: true
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: rook-ceph-block
              resources:
                requests:
                  storage: 100Gi
        # tolerations:
        # - key: "arm"
        #   operator: "Exists"
  valuesFrom:
  - secretKeyRef:
      name: prometheus-operator-helm-values